CREATE TABLE public.test (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY (id)
);

CREATE OR REPLACE FUNCTION create_hello(p_title text)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.test (title) VALUES (p_title);
END;
$$;
