CREATE TABLE public.test (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT test_pkey PRIMARY KEY (id)
);
