CREATE TABLE IF NOT EXISTS some_table (
    class_result_id bigint GENERATED BY DEFAULT AS IDENTITY,
    class_run_id integer,
    CONSTRAINT some_table_pkey PRIMARY KEY (class_result_id, class_run_id)
) PARTITION BY LIST (class_run_id);
