CREATE TABLE public.some_table (
    class_result_id bigint GENERATED BY DEFAULT AS IDENTITY,
    class_run_id integer,
    PRIMARY KEY (class_result_id, class_run_id)
) PARTITION BY LIST (class_run_id);
